# This file includes values for adversarial features (here e.g. src2dst_max_ps) 
# The values will be realized in DeepRed C2 communication in the correspodning direction src2dst (bot to C2 ) or wise versa.
# i
src2dst_max_ps: [
      622.2105, 751.27386, 788.03485, 1471.9115, 960.26385, 809.9465, 1033.4388, 1042.5073,
      1115.0743, 1284.9279]
