
# This configuration file is loaded by bot.py and is used to define parameters for bot-to-C2 (Command and Control) communication. Specifically, it contains perturbation values for adversarial feature manipulation—such as src2dst_max_ps—to simulate realistic yet evasive communication patterns.
# The perturbation values are applied during DeepRed C2 communication in the corresponding direction, either src2dst (bot to C2) or dst2src (C2 to bot).
# If features like *_bytes or *_max_ps are targeted, random strings will be padded to the message being sent in the respective direction. If *_packets features are involved, additional packets will be inserted into the communication accordingly.
# The following adversarial features are subject to perturbation: 
#[ 'src2dst_packets', 'src2dst_bytes', 'src2dst_max_ps', 'dst2src_packets', 'dst2src_bytes', 'dst2src_max_ps' ]


# set define adversarial features and their perturbation values (DeepRed paper suggests either single or max 2 features to be set)
src2dst_max_ps: [ 300.9279]
src2dst_packets: [ 20.0]

