#-------base command
rce:
  network_discovery: ["hostname -I","nmcli device status","nmcli connection show","ip route show","ip addr show","ss -anp","ifconfig", "netstat -tuln", "ss -tuln" , "ss -tuln", "arp -a", "ip link show"]
  account_discovery: ["last","grep -E '^sudo|^admin' /etc/group","whoami", "W","who","id", "getent host" ,"getent group" ,"getent passwd",  "cat /etc/passwd" , "cat /etc/group"]
  file_and_directory_discovery: ["dir",  "find /home/user1/ -type f",  "ls -alR",  "df -h", " du -sh /home/",  "ls -lh",  "tree" ]
  system_information_discovery: ["uname -a","vmstat","free -h","cat /etc/os-release","hostnamectl", "dmesg | head -5","lshw","lsb_release -a","cat /proc/cpuinfo","cat /proc/meminfo","uptime","uptime -p"]
  system_service_discovery: ["service --status-all","ps -ef","ps aux", "systemctl is-active ssh","ps aux --sort=-%cpu" ]

#-------exfiltration
# Set the folder address where exfiltrated data will be stored
exfil_data_address: "deepred-c2/sample_file_to_exfil"


